### ISSUE TITLE
3.0 build

### ISSUE THREAD

**Issue by dothebart** [gbevan/portage-arangodb-overlay#2]
Hi, 
you can drop the dependency to go on the 3.0 receipe. its not needed anymore.

you can completely remove the options of this line: `#econf --localstatedir="${EPREFIX}"/var --enable-all-in-one-v8 --enable-all-in-one-libev --enable-all-in-one-icu || die "configure failed"`
its not needad anymore.

In the other packages we made most of it `arangodb3` in order to make clear that its not compatible with 2.x.

Quoting https://build.opensuse.org/package/view_file/home:fceller:versionX/arangodb-3.x/debian.rules?expand=1 :

```
     CC="$(CC)" CFLAGS="$(CFLAGS)" CXX="$(CXX)" CXXFLAGS="$(CXXFLAGS)" V8_CFLAGS="$(V8_CFLAGS)" V8_CXXFLAGS="$(V8_CXXFLAGS)" V8_LDFLAGS="$(V8_LDFLAGS)" \
    /usr/bin/cmake \
            -DVERBOSE=On \
            -DUSE_OPTIMIZE_FOR_ARCHITECTURE=Off \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_FLAGS="$(CFLAGS)" \
            -DCMAKE_CXX_FLAGS="$(CXXFLAGS)" \
            -DETCDIR=/etc \
            -DVARDIR=/var \
            -DCMAKE_INSTALL_PREFIX:PATH=/usr \
            -DCMAKE_SKIP_RPATH:BOOL=ON \
            .
```

should get you a working 3.0 support.

Thanks for your support ;-)

**Comment by gbevan** [comment]
Cheers for this - I had been struggling to build a 3.0.0 ebuild previously and had put this on hold due to other priorities.  3.0.3 with the above advice is now compiling successfully, and I am currently testing the restructuring for a arangodb3 ebuild package.

Many Thanks, your help is very much appreciated :-)

**Comment by dothebart** [comment]
okies, glad I could help ;-)
Cheers from cologne from the ArangoDB Team and thanks for your effort.
