### ISSUE TITLE
arangodb3-3.1.3 compilation failed

### ISSUE THREAD

**Issue by yak01** [gbevan/portage-arangodb-overlay#3]
Hi folks,
on my system the compilation of arangodb3-3.1.3 failed, but I'm not really capable to retrieve why. The build log doesn't show an obvious error to me, but I hope some expert can help me. Since I don't know what's relevant, I attach the emerge log, the build log, and the build environment. If additional information is needed, simply ask.

[build.txt](https://github.com/gbevan/portage-arangodb-overlay/files/658958/build.txt)
[emerge.txt](https://github.com/gbevan/portage-arangodb-overlay/files/658959/emerge.txt)
[environment.txt](https://github.com/gbevan/portage-arangodb-overlay/files/658957/environment.txt)

UPDATE: The build log seems to indicate that eliptic curves need to be supported.

**Comment by gbevan** [comment]
Hi, I found a similar hit here - https://forums.gentoo.org/viewtopic-t-1044326-start-0.html
It suggests re-emerging openssl without the "bindist" USE flag.

**Comment by yak01** [comment]
Indeed, this worked out. I hope this can be integrated into the overlay somehow.

**Comment by gbevan** [comment]
Good idea!  I've added -bindist as an openssl exclusion dependency to the latest ebuild for arangodb 3.1.5.  Its under testing tonight...

thx

**Comment by gbevan** [comment]
3.1.5 ebuild tested and released
