### ISSUE TITLE
Digest verification failed for arangodb3-3.2.8.ebuild

### ISSUE THREAD

**Issue by Evi1M4chine** [gbevan/portage-arangodb-overlay#4]
!!! Digest verification failed:
!!! /var/lib/layman/gbevan-arangodb/dev-db/arangodb3/arangodb3-3.2.8.ebuild
!!! Reason: Filesize does not match recorded size
!!! Got: 1587
!!! Expected: 1588

(I synced just a couple of minutes ago.)

**Comment by gbevan** [comment]
i've regenerated the manifest - please try again
