### ISSUE TITLE
Add support for GCC 7.x.

### ISSUE THREAD

**Issue by Evi1M4chine** [gbevan/portage-arangodb-overlay#5]
Compilation on Gentoo currently fails with:

    CMake Error at CMakeLists.txt:357 (message):
      ArangoDB doesn't support GCC 7.0 yet.

At least for version 3.2.6. The latest ebuild available currently, that has a valid manifest.

**Comment by gbevan** [comment]
this looks like an ArangoDB itself issue, not this ebuild.  Perhaps you could raise this with them at https://github.com/arangodb/arangodb .  
fyi - I'll be looking at updating the 3.2 and 3.3 ebuilds in the near future.
